import React, { Component, useState } from 'react'
import { Text, View, Image, StyleSheet,Dimensions, TouchableOpacity, ScrollView} from 'react-native'
import {useDispatch} from 'react-redux'

const assestsPath = "../../../assets/";

const isCloseToBottom = ({layoutMeasurement, contentOffset, contentSize}) => {
    return layoutMeasurement.height + contentOffset.y >=
      contentSize.height;
  };

function Agreement({navigation}){
    const dispatch = useDispatch()
    const [isAccepted, setIsAccepted] = useState(false)
    const onPressAgreeBtn = () => {
      dispatch.user.setAgreement({agreement:true})
      .then(
      ()=>navigation.navigate("LogIn"))
    }
    const NavBar = () => {

    }

    const agreementView = () => {
      return(
        <View style={styles.container}>
            {/* <Text style={styles.title}>Terms of Service</Text> */}
            <ScrollView 
            enableOnAndroid
            style={styles.tcContainer}
            scrollEventThrottle={16}
            onScroll={({nativeEvent}) => {
                if (isCloseToBottom(nativeEvent)) {
                  setIsAccepted(true)
                }
              }}
            >
                
                <Text>
                {/* Last Updated: April 01, 2020

Please read these Terms of Service (“Terms”) carefully as they contain important information about your legal rights. When you express consent to these Terms by registering, accessing, or using the Roomon Platform, you agree to comply with and be bound by these Terms.
Thank you for using Roomon!

These Terms constitute a legally binding agreement ("Agreement") between you and Roomon (as defined below) governing your access to and use of the Roomon website, including any subdomains thereof, and any other websites through which Roomon makes its services available (collectively, "Site"), our mobile, tablet and other smart device applications, and application program interfaces (collectively, "Application") and all associated services (collectively, "Roomon Services"). The Site, Application and Roomon Services together are hereinafter collectively referred to as the “Roomon Platform”. Our collection and usage of your personally identifiable information in your regard to your access to the Roomon Platform is written in our Privacy Policy.

When these Terms mention “Roomon,” “we,” “us,” or “our,” it refers to the Roomon company you are contracting with. 
Hosts alone are responsible for identifying, understanding, and complying with all laws, rules and regulations that apply to their Listings. 

1. Modification of these Terms
Roomon reserves the right to modify these Terms at any time in accordance with this provision. If we make changes to these Terms, we will post the revised Terms on the Roomon Platform and update the “Last Updated” date at the top of these Terms. We will also provide you with notice of the modifications by email at least thirty (30) days before the date they become effective. If you disagree with the revised Terms, you may terminate this Agreement with immediate effect. We will inform you about your right to terminate the Agreement in the notification email. If you do not terminate your Agreement before the date the revised Terms become effective, your continued access to or use of the Roomon Platform will constitute acceptance of the revised Terms.

2. Definitions.
Capitalized terms shall have the meanings set forth in this section, or in the sections where they are used.
ROOMON and ROOMON APP. ROOMON also refers to the trademark used to refer to the Roomon Platform, the Site and the Application through which the Roomon Services are provided, whether registered or unregistered at any time hereafter with the applicable governmental authorities in such jurisdictions as deemed necessary by Roomon, and Roomon App equally has the same use and definition herein.

MEMBER. A user who completes Roomon’s registration process as described under “Account Registration” below, creating a Roomon Account for use on the Roomon Platform.
LISTING. A rental that is listed as available for rent via the Roomon Platform.
LANDLORD. A User who creates a Listing for rent via the Roomon Platform. This includes any agent or property manager who, as an employee, contractor or agent for a Landlord creates and manages Listings on the Roomon Platform on behalf of such parties with the authority of such Landlord.
RENTER. A Member who desires to rent or lease a Listing.
TENANT. A Member who has entered into a Tenancy Agreement with a Landlord via the Roomon Platform.
USER. Any user of the Roomon Services provided through the Roomon Platform, which can include a Member, a Member who is a Renter, a Tenant, a Landlord, or an agent on a Landlord’s behalf.
USER CONTENT. All information and data, including text, images, photos, videos, audio, documents and any User-generated content in any media and format that a User of the Roomon Services posts, uploads, publishes, submits, makes available or transmits to be made available through the Site, Application or Roomon Platform generally.
In these Terms, words referring to a singular number include the plural and vice versa, words importing any gender include all genders and words importing persons include all legal persons, which means individuals and legal entities of all types. The term “including” means “including without limiting the generality of the foregoing”.

3. Scope of Roomon Services
The Roomon Platform is an online hub that connects Renters and Landlords, by matching prospective Renters with suitable Listings. The Roomon Platform facilitates parts of the residential tenancy process, such as providing Listing searches, communication with each other, and submitting tenancy applications. On the Roomon Platform prospective Renters will be able to view the profiles of Landlords according to their criteria and the Listings they upload (for possible rental properties), and Landlords will be able to view the profiles of Renters (for appropriate Renters). Users must exercise their own caution when using the Roomon Platform to view others’ profiles. 
As the provider of the Roomon Platform, Roomon does not own, create, sell, resell, provide, control, manage, offer, deliver, or supply any Listings, nor is Roomon a party to any rental, lease, property management or other agreement between Users in relation to any Listings. Landlords alone are responsible for their Listings and whatever services they may provide to any Renters. When Users enter a Tenancy Agreement, they are entering into a contract directly with each other. Roomon is not and does not become a party to or other participant in any contractual relationship between Members, nor is Roomon a real estate broker, agent, property manager, insurance provider, or other professional advisors. Roomon is not acting as an agent in any capacity for any User.  

While we may help facilitate the resolution of disputes, Roomon has no control over and does not guarantee (i) the existence, quality, safety, suitability, or legality of any Listings, (ii) the truth or accuracy of any Listing descriptions, Ratings, Reviews, or other Member Content (as defined below), or (iii) the performance or conduct of any Member or third party. Roomon does not endorse any Member, Listing or Host Services. Any references to a Member being "verified" (or similar language) only indicate that the Member has completed a relevant verification or identification process and nothing else. Any such description is not an endorsement, certification or guarantee by Roomon about any Member, including of the Member's identity or background or whether the Member is trustworthy, safe or suitable. You should always exercise due diligence and care when deciding whether to stay in an Accommodation, participate in an Experience or Event or use other Host Services, accept a booking request from a Guest, or communicate and interact with other Members, whether online or in person. Verified Images (as defined below) are intended only to indicate a photographic representation of a Listing at the time the photograph was taken, and are therefore not an endorsement by Roomon of any Host or Listing.

The Roomon Platform enables communication between Landlords and Renters both via the Roomon Platform and offline amongst themselves. Accordingly, we disclaim any liability for the disclosure to, use and retention of any Personal Information between Landlords and Renters whose contact may have originated from the Roomon Platform. Landlords in British Columbia are required to obtain signed disclosure forms from prospective Tenants before requesting any information from the prospective Tenant, which forms can be retrieved from the Real Estate Council of British Columbia (“RECBC”) by following these links to the Disclosure of Representation in Trading Services and the Disclosure of Risks to Unrepresented Parties (together, “Forms”). Roomon is expressly not responsible for ensuring that these Forms are reviewed and signed by prospective Tenants; this is the sole responsibility of each Landlord (via their property manager or otherwise) to obtain from prospective Tenants and retain and or provide to the RECBC as required.

To promote the Roomon Platform and to increase the exposure of Listings to potential Renters, Listings and other Member Content may be displayed on other websites, in applications, within emails, and in online and offline advertisements. To assist Members who speak different languages, Listings and other Member Content may be translated, in whole or in part, into other languages. Roomon cannot guarantee the accuracy or quality of such translations and Members are responsible for reviewing and verifying the accuracy of such translations. The Roomon Platform may contain translations powered by Google. Google disclaims all warranties related to the translations, express or implied, including any warranties of accuracy, reliability, and any implied warranties for merchantability, fitness for a particular purpose and non-infringement.

The Roomon Platform may contain links to third-party websites or resources (“Third-Party Services”). Such Third-Party Services may be subject to different terms and conditions and privacy practices. Roomon is not responsible or liable for the availability or accuracy of such Third-Party Services, or the content, products, or services available from such Third-Party Services. Links to such Third-Party Services are not an endorsement by Roomon of such Third-Party Services.

Due to the nature of the Internet, Roomon cannot guarantee the continuous and uninterrupted availability and accessibility of the Roomon Platform. Roomon may restrict the availability of the Roomon Platform or certain areas or features thereof, if this is necessary in view of capacity limits, the security or integrity of our servers, or to carry out maintenance measures that ensure the proper or improved functioning of the Roomon Platform. Roomon may improve, enhance and modify the Roomon Platform and introduce new Roomon Services from time to time.

3. Eligibility, Registration, Verification
You must be at least 18 years of age to use the Service. By agreeing to these Terms of Use, you represent and warrant tha you are at least 18 years of age, you have not previously been suspended or removed from the Services, your registration and your use of the Services is in compliance with all applicable laws and regulations, and that you have both the legal authority and capacity to enter a legally binding contract. To access some features of the Services, you may be required to register for an account. When you register for an account, you may be required to provide us with some information about yourself, such as email address or other contact information. You agree that the information you provide is accurate and that you will keep it accurate and up-to-date at all times. When you register, you may be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password, and you are responsible for all actions taken via your account. You may not share your user account(s) with others. Unless you have entered into a commercial agreement with Roomon Group permitting you to use the Services for transactions on behalf of another person, you may only use the Services for transactions on your own behalf, and not on behalf of any other person. In some cases, Roomon Accounts may be created for a prospective Tenant by a Landlord based upon the prospective Tenant’s prior written consent and Personal Information provided to the Landlord in a hard copy or other tenancy application. The Landlord may then create a Roomon Account for the prospective Tenant when the Landlord creates a Tenancy Agreement in the Roomon Account and links such Tenancy Agreement with the Roomon Account created for the prospective Tenant, and upon the prospective Tenant’s receipt of the login details for the Roomon Account, the prospective Tenant will be able to change the password within the Roomon Account, update their Personal Information, review the Tenancy Agreement and sign within the Roomon Platform. The prospective Tenant will also be able to review and consent to both the Privacy Policy and these Terms in relation to their usage of the Roomon Platform.

User verification on the Internet is difficult and we do not assume any responsibility for the confirmation of any Member’s identity. Notwithstanding the above, for transparency and fraud prevention purposes, and as permitted by applicable laws, we may, but have no obligation to (i) ask Members to provide a form of government identification or other information or undertake additional checks designed to help verify the identities or backgrounds of Members, (ii) screen Members against third party databases or other sources and request reports from service providers, and (iii) where we have sufficient information to identify a Member, obtain reports from public records of criminal convictions or sex offender registrations or an equivalent version of background or registered sex offender checks in your local jurisdiction (if available).

To maintain a safe and trusted environment, Roomon confirms your identity through a manual review of the screen capture of the government-issued identification card or other authentication information uploaded by you, comparing it to the account information uploaded by you when you create a Roomon Account. The screen capture information will not be included in your Roomon Profile or in other areas. However, by uploading this information we are able to maintain a trusted environment, and protect against identity theft and other fraudulent theft by confirming Users’ identities.
The access to or use of certain areas and features of the Roomon Platform may be subject to separate policies, standards or guidelines, or may require that you accept additional terms and conditions, before you can access the relevant areas or features of the Roomon Platform. If there is a conflict between these Terms and terms and conditions applicable to a specific area or feature of the Roomon Platform, the latter terms and conditions will take precedence with respect to your access to or use of that area or feature, unless specified otherwise in the latter terms and conditions.

4. Using the App through Mobile Applications
To use any mobile application feature of the Services (each, an “App”), you must have a compatible mobile device. Roomon Group does not warrant that any App will be compatible with your mobile device. You may use mobile data in connection with an App and may incur additional charges from your wireless provider for using an App. You agree that you are solely responsible for any applicable charges. Roomon Group may update any app and may automatically electronically update the version of any App that you have installed on a mobile device. You consent to all automatic upgrades, and understand that these Terms of Use will apply to all updated versions of an App. Any third-party open source software included in an App is subject to the applicable open source license and may be available directly from the creator under an open source license. These Terms of Use do not apply to your use of software obtained from a third-party source under an open source license.
	
If you access or download the Application from the Apple App Store, you agree to Apple’s Licensed Application End User License Agreement. Some areas of the Roomon Platform implement Google Maps/Earth mapping services, including Google Maps API(s). Your use of Google Maps/Earth is subject to the Google Maps/Google Earth Additional Terms of Service.

5. Content
Roomon may, at its sole discretion, enable Members to (i) create, upload, post, send, receive and store content, such as text, photos, audio, video, or other materials and information on or through the Roomon Platform ("Member Content"); and (ii) access and view Member Content and any content that Roomon itself makes available on or through the Roomon Platform, including proprietary Roomon content and any content licensed or authorized for use by or through Roomon from a third party ("Roomon Content" and together with Member Content, "Collective Content").

The Roomon Platform, Roomon Content, and Member Content may in its entirety or in part be protected by copyright, trademark, and/or other laws of Canada and other countries. You acknowledge and agree that the Roomon Platform and Roomon Content, including all associated intellectual property rights, are the exclusive property of Roomon and/or its licensors or authorizing third-parties. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Roomon Platform, Roomon Content or Member Content. All trademarks, service marks, logos, trade names, and any other source identifiers of Roomon used on or in connection with the Roomon Platform and Roomon Content are trademarks or registered trademarks of Roomon in Canada and abroad. Trademarks, service marks, logos, trade names and any other proprietary designations of third parties used on or in connection with the Roomon Platform, Roomon Content, and/or Collective Content are used for identification purposes only and may be the property of their respective owners.

You will not use, copy, adapt, modify, prepare derivative works of, distribute, license, sell, transfer, publicly display, publicly perform, transmit, broadcast or otherwise exploit the Roomon Platform or Collective Content, except to the extent you are the legal owner of certain Member Content or as expressly permitted in these Terms. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Roomon or its licensors, except for the licenses and rights expressly granted in these Terms.

Subject to your compliance with these Terms, Roomon grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable license to (i) download and use the Application on your personal device(s); and (ii) access and view any Collective Content made available on or through the Roomon Platform and accessible to you, solely for your personal and non-commercial use.

By creating, uploading, posting, sending, receiving, storing, or otherwise making available any Member Content on or through the Roomon Platform, you grant to Roomon a non-exclusive, worldwide, royalty-free, irrevocable, perpetual (or for the term of the protection), sub-licensable and transferable license to such Member Content to access, use, store, copy, modify, prepare derivative works of, distribute, publish, transmit, stream, broadcast, and otherwise exploit in any manner such Member Content to provide and/or promote the Roomon Platform, in any media or platform. Insofar as Member Content (including Verified Images) includes personal information, such Member Content will only be used for these purposes if such use complies with applicable data protection laws in accordance with our Privacy Policy. Unless you provide specific consent, Roomon does not claim any ownership rights in any Member Content and nothing in these Terms will be deemed to restrict any rights that you may have to use or exploit your Member Content.

Roomon may offer Hosts the option of having professional photographers take photographs of their Host Services, which are made available by the photographer to Hosts to include in their Listings with or without a watermark or tag bearing the words "Roomon.com Verified Photo" or similar wording ("Verified Images"). You are responsible for ensuring that your Host Service is accurately represented in the Verified Images and you will stop using the Verified Images on or through the Roomon Platform if they no longer accurately represent your Listing, if you stop hosting the Host Service featured, or if your Roomon Account is terminated or suspended for any reason. You acknowledge and agree that Roomon shall have the right to use any Verified Images in accordance with Section 5.5 for advertising, marketing and/or any other business purposes in any media or platform, whether in relation to your Listing or otherwise, without further notice or compensation to you. Where Roomon is not the exclusive owner of Verified Images, by using such Verified Images on or through the Roomon Platform, you grant to Roomon an exclusive, worldwide, royalty-free, irrevocable, perpetual (or for the term of the protection), sub-licensable and transferable license to use such Verified Images for advertising, marketing and/or any other business purposes in any media or platform, whether in relation to your Listing or otherwise, without further notice or compensation to you. Roomon in turn grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable license to use Verified Images outside of the Roomon Platform solely for your personal and non-commercial use.

You are solely responsible for all Member Content that you make available on or through the Roomon Platform. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all Member Content that you make available on or through the Roomon Platform or you have all rights, licenses, consents and releases that are necessary to grant to Roomon the rights in and to such Member Content, as contemplated under these Terms; and (ii) neither the Member Content nor your posting, uploading, publication, submission or transmittal of the Member Content or Roomon's use of the Member Content (or any portion thereof) as contemplated under these Terms will infringe, misappropriate or violate a third party's patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.

You will not post, upload, publish, submit or transmit any Member Content that: (i) is fraudulent, false, misleading (directly or by omission or failure to update information) or deceptive; (ii) is defamatory, libelous, obscene, pornographic, vulgar or offensive; (iii) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or threatening or promotes violence or actions that are threatening to any other person or animal; (v) promotes illegal or harmful activities or substances; or (vi) violates Roomon’s Content Policy or any other Roomon policy. Roomon may, without prior notice, remove or disable access to any Member Content that Roomon finds to be in violation of applicable law, these Terms or Roomon’s then-current Policies or Standards, or otherwise may be harmful or objectionable to Roomon, its Members, third parties, or property.

Roomon respects copyright law and expects its Members to do the same. If you believe that any content on the Roomon Platform infringes copyrights you own in any material, please notify us at business.roomx@gmail.com

6. Responsibility for Content
When creating a Listing through the Roomon Platform you must (i) provide complete and accurate information about your Host Service (such as listing description, location, and calendar availability), (ii) disclose any deficiencies, restrictions (such as house rules) and requirements that apply (such as any minimum age, proficiency or fitness requirements for an Experience) and (iii) provide any other pertinent information requested by Roomon. You are responsible for keeping your Listing information (including calendar availability) up-to-date at all times.

You are solely responsible for setting a price (including any Taxes if applicable, or charges such as cleaning fees) for your Listing (“Listing Fee”). Once a Guest requests a booking of your Listing, you may not request that the Guest pays a higher price than in the booking request.

Any terms and conditions included in your Listing, in particular in relation to cancellations, must not conflict with these Terms or the relevant cancellation policy for your Listing.

Pictures, animations or videos (collectively, "Images") used in your Listings must accurately reflect the quality and condition of your Host Services. Roomon reserves the right to require that Listings have a minimum number of Images of a certain format, size and resolution.

The placement and ranking of Listings in search results on the Roomon Platform may vary and depend on a variety of factors, such as Guest search parameters and preferences, Host requirements, price and calendar availability, number and quality of Images, customer service and cancellation history, Reviews and Ratings, type of Host Service, and/or ease of booking. More information about the factors that determine how your Listing appears in search results can be found on our help center.

When you accept or have pre-approved a booking request by a Guest, you are entering into a legally binding agreement with the Guest and are required to provide your Host Service(s) to the Guest as described in your Listing when the booking request is made. You also agree to pay the applicable Host Fee and any applicable Taxes.

Roomon recommends that Hosts obtain appropriate insurance for their Host Services. Please review any respective insurance policy carefully, and in particular make sure that you are familiar with and understand any exclusions to, and any deductibles that may apply for, such insurance policy, including, but not limited to, whether or not your insurance policy will cover the actions or inactions of Guests (and the individuals the Guest has booked for, if applicable) while staying at your Accommodation or participating in your Experience, Event or other Host Service.

Unless expressly allowed by Roomon, you may not list more than one Accommodation per Listing.
If you choose to require a security deposit for your Accommodation, you must specify this in your Listing ("Security Deposit"). Hosts are not allowed to ask for a Security Deposit (i) after a booking has been confirmed or (ii) outside of the Roomon Platform.

You represent and warrant that any Listing you post and the booking of, or a Guest's stay at, an Accommodation will (i) not breach any agreements you have entered into with any third parties, such as homeowners association, condominium, or other agreements, and (ii) comply with all applicable laws (such as zoning laws), Tax requirements, and other rules and regulations (including having all required permits, licenses and registrations). As a Host, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who reside at or are otherwise present at the Accommodation at your request or invitation, excluding the Guest and any individuals the Guest invites to the Accommodation.

7. Terminations/ Changes to Agreement 
Except as stated in separate product-specific agreements, you may terminate your account at any time by contacting business.roomxapp@gmail.com. If you terminate your account, you remain obligated to pay all outstanding fees, if any, incurred prior to termination relating to your use of the Services. If you violate any provision of these Terms of Use, your permission from Roomon Group to use the Services will terminate automatically. In addition, Roomon Group may in its sole discretion terminate your account on the Services or suspend or terminate your access to the Services at any time for any reason, with or without notice. Roomon Group may alter, suspend or discontinue the Services or any portion of the Services without notice. Roomon Group will not be liable whatsoever for any change to the Services or any suspension or termination of your access to or use of the Services. Roomon Group reserves the right to change these Terms of Use at any time in its sole discretion on a going-forward basis. We will make commercially reasonable efforts to notify you of any material changes to these Terms of Use. Your continued use of the Services after updates are effective will represent your agreement to the revised version of these Terms of Use. Your continued use of the Services after the effectiveness of such changes will constitute acceptance of and agreement to any such changes. You further waive any right you may have to receive specific notice of such changes to these Terms of Use. You are responsible for regularly reviewing these Terms of Use.

8. Fees
You may be required to pay fees to access certain features of the Services. All fees are in U.S. dollars and are non-refundable. If Roomon Group changes the fees for all or part of the Services, including by adding fees or charges, Roomon Group will provide you advance notice of those changes. If you do not accept the changes, Roomon Group may discontinue providing the applicable part of the Services to you. Roomon Group’s authorized third-party payment processor will charge the payment method you specified at the time of purchase. You authorize Roomon Group to charge all fees as described in these Terms of Use for the Services you select to that payment method. If you pay any fees with a credit card, Roomon Group may seek pre-authorization of your credit card account before your purchase to verify that the credit card is valid and has the necessary funds or credit available to cover your purchase.

Roomon may charge fees to Hosts ("Host Fees") and/or Guests ("Guest Fees") (collectively, "Service Fees") in consideration for the use of the Roomon Platform. More information about when Service Fees apply and how they are calculated can be found on our Service Fees page.

Any applicable Service Fees (including any applicable Taxes) will be displayed to a Host or Guest prior to publishing or booking a Listing. Roomon reserves the right to change the Service Fees at any time, and will provide Members adequate notice of any fee changes before they become effective. Such fee changes will not affect any bookings made prior to the effective date of the fee change.

You are responsible for paying any Service Fees that you owe to Roomon. The applicable Service Fees (including any applicable Taxes) are collected by Roomon Payments. Roomon Payments will deduct any Host Fees from the Listing Fee before remitting the payout to the Host. Any Guest Fees are included in the Total Fees collected by Roomon Payments. Except as otherwise provided on the Roomon Platform, Service Fees are non-refundable.

The Services may include features that allow for automatically recurring payments for periodic charges (“Subscription Service”). If you decide to activate a Subscription Service, you authorize Roomon Group to periodically charge, on a going-forward basis and until cancellation of either the recurring payments or your account, all accrued sums on or before the payment due date for the accrued sums. The subscription will continue unless and until you cancel your subscription, or we terminate it. You must cancel your subscription before it renews in order to avoid billing of the next periodic subscription fee to your account. We will bill the periodic subscription fee to the payment method you provide to us during registration (or to a different payment method if you change your payment information). Roomon Group may change the subscription fee for any subsequent subscription period but will provide you advance notice of any increase before it applies. You may cancel a Subscription Service by contacting us at: business.roomxapp@gmail.com, by contacting your business consultant, or through your settings page for the paid feature.

9. User Materials
Certain portions of the Services may allow users to upload or otherwise provide to Roomon Group images, photos, video, data, text, listings and other content (“User Materials”). By uploading or otherwise providing User Materials to the Services, you grant Roomon Group an irrevocable, perpetual, royalty-free worldwide license to: (i) use, copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, modify, prepare derivative works of or incorporate into other works, and translate your User Materials, in connection with the Services, or in any other media; and (ii) sublicense these rights, to the maximum extent permitted by applicable law. Roomon Group will not pay you for your User Materials or to exercise any rights related to your User Materials set forth in the preceding sentence. Roomon Group may remove or modify your User Materials at any time. You are solely responsible for all User Materials made through your user account(s) on the Services or that you otherwise make available through the Services. For all User Materials, you represent and warrant that you are the creator and owner of the User Materials, or have the necessary licenses, rights, consents, and permissions (including all permissions required under applicable privacy and intellectual property law) to authorize Roomon and other users to access and use your User Materials as necessary to exercise the licenses granted by you under these Terms of Use.  Roomon will not use client contact information that is uploaded by agents into the Roomon Platform without the client’s permission.

Roomon is under no obligation to edit or control your User Materials or the User Materials of any other User and will not be in any way responsible or liable for any User Materials. Roomon may, however, at any time and without prior notice, screen, remove, edit, or block any User Materials on the Services, including User Materials, that in Roomon’s sole judgment violate these Terms of Use or are otherwise objectionable. You understand that when using the Services, you may be exposed to User Materials of other users and acknowledge that User Materials may be inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you may have against Roomon with respect to User Materials. Roomon expressly disclaims any and all liability in connection with User Materials. If notified by a user or content owner that User Materials allegedly do not conform with these Terms of Use, Roomon may investigate the allegation and determine in Roomon’s sole discretion whether to remove the User Materials, which Roomon reserves the right to do at any time and without notice. For more information on Roomon’s handling of infringing content, please see our Privacy Policy.

10. 3rd Party Information */}
Our Services that we provide may include links to third-party products, services and Web sites, as well as materials provided by third parties, and may include functionality that allows for the distribution of your User Materials or your personal information (collectively, your “User Information”) to third parties not under Roomon Group’s control (each, a “Third-Party Provider”). Third-Party Providers are solely responsible for their services. You are responsible for your use and submission of User Information to any third-party, and your dealings or business conducted with any third party arising in connection with the Services are solely between you and such third party. Your use of third-party sites, services, or products may be subject to associated third-party terms of use and privacy policies or other agreements, which you are solely responsible for complying with. Roomon does not endorse, and takes no responsibility for such products, services, Web sites, and materials, or a Third-Party Provider’s use of your User Information. By using a tool that allows for User Information to be transferred, you agree that Roomon may transfer the applicable User Information or other information to the applicable third-parties, which are not under the control of Roomon. If you submit a contact form or otherwise indicate your interest in contacting a Third-Party Provider, you may receive telemarketing calls from the Third-Party Provider using the contact information you provided. Third-Party Providers may keep your contact information and any other information received by the Third-Party Provider in processing a contact or other request form. Roomon is not responsible for any damages or costs of any type arising out of or in any way connected with your dealings with these third parties.

If you choose to contact a bank, lender, financial institution, originator, loan broker, or other mortgage professional through the Services by filling out a contact, other request form or otherwise indicating your interest in contacting (or being contacted by) a Third-Party Provider (including requests for rate quotes) on the Services, you authorize Roomon (and, in the event that the Third-Party Provider is a bank, lender, financial institution, originator, loan broker or other mortgage professional, each a “Lender”, you authorize Roomon in particular) to provide the information you submit to the Third-Party Provider. If you include your name, contact information and other information in a request, your identity will no longer be anonymous to the Third-Party Provider. Your submission of information and any request for quotes through the Services is not an application for credit. Roomon is only providing an administrative service to consumers and participating Lenders. Decisions regarding Lenders contacting consumers are made by participating Lenders and not Roomon. By using these features, the disclosures and consent required under certain state laws are deemed to be provided, received, and agreed to. Interest rates displayed through the Services are for information purposes only and reflect non-binding customized quotes of the terms a Lender might offer a borrower fitting a consumer’s anonymous profile. Actual interest rates may vary. Loan approval standards are established and maintained solely by individual Lenders. Consumers should rely on their own judgment in deciding which available loan product, terms, and Third-Party Provider best suit their needs and financial means. Roomon: (a) is not a Lender, loan originator, loan processor or underwriter; (b) does not aid or assist borrowers in obtaining loans, solicit borrowers or Lenders for loans, offer or negotiate terms of loans; (c) does not take mortgage applications, make loans or credit decisions or pre-approve borrowers for loans; (d) is not an agent of either any consumer or any Lender; (e) does not endorse, refer or recommend any Third-Party Provider that pays Roomon Group or the products of any Third-Party Provider that pays Roomon; (f) is not responsible for any errors or delays caused by consumers or any Third-Party Provider in the loan process; and (g) does not guarantee offer of, or acceptance into, any particular loan program or specific loan terms, conditions, or rates with any Third-Party Provider, or that any rates or terms will be the best available.

11. Intellectual Property Notices. 
The Services are owned and operated by Roomon Group. The user interfaces, design, information, data, code, products, software, graphics, and all other elements of the Services (“Roomon Group Materials”) provided by Roomon Group are protected by intellectual property and other laws and are the property of Roomon Group or Roomon Group’s third-party licensors. Except as expressly allowed by these Terms of Use, you may not make use of the Roomon Group Materials, and Roomon Group reserves all rights to the Roomon Group Materials and Services not granted expressly in these Terms of Use.

12. Indemnification
You agree to indemnify, defend, and hold harmless Roomon Group, its affiliates, and their respective directors, officers, employees, and agents from any and all claims and demands made by any third party due to or arising out of: (a) your access to or use of the Services; (b) your breach of these Terms of Use; (c) your violation of any law or the rights of a third party; (d) any dispute or issue between you and any third party; (e) any User Materials you upload to, or otherwise make available through, the Services; (f) your willful misconduct; and (g) any other party’s access to and/or use of the Services using your account and password. Roomon Group reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in that case, you agree to corporate with Roomon Group’s defense of that claim.

These Terms of Use are governed by the laws of the province of British Columbia, without giving effect to its conflict of laws provisions. You agree to submit to the personal and exclusive jurisdiction and venue in the provincial and federal courts sitting in British Columbia for any and all disputes, claims and actions arising from or in connection with the Services and/or these Terms of Use. Roomon operates the Services from its offices in British Columbia, and we make no representation that the Services are appropriate or available for use in other locations.

You agree not to export from anywhere any part of the Services provided to you, or any direct product thereof, except in compliance with, and with all licenses and approvals required under, applicable export laws, rules and regulations. All Services used by the Canada Government are provided with the commercial license rights described herein. These Terms of Use may only be amended by a written agreement signed by authorized representatives of the parties to these Terms of Use. If any part of these Terms of Use is determined to be invalid or unenforceable, then the invalid or unenforceable provision will be replaced with a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms of Use will continue in effect. The section titles in these Terms of Use are solely used for the convenience of the parties and have no legal or contractual significance. Roomon Group may assign this Agreement, in whole or in part, at any time with or without notice to you. You may not assign these Terms of Use, or assign, transfer or sublicense your rights, if any, in the Services. Roomon Group’s failure to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches. Except as expressly stated herein, these Terms of Use, and all expressly incorporated terms and agreements, constitute the entire agreement between you and Roomon Group with respect to the Services and supersede all prior or contemporaneous communications of any kind between you and Roomon Group with respect to the Services. 

13. Limitation of Liabilities
ROOMON GROUP PROVIDES THE SERVICES “AS IS,” “WITH ALL FAULTS” AND “AS AVAILABLE,” AND THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY, AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ROOMON GROUP AND ITS SUPPLIERS MAKE NO REPRESENTATIONS, WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED. ROOMON GROUP AND ITS SUPPLIERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OR CONDITIONS, EXPRESS, STATUTORY AND IMPLIED, INCLUDING WITHOUT LIMITATION: (A) WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, WORKMANLIKE EFFORT, ACCURACY, TITLE, QUIET ENJOYMENT, NO ENCUMBRANCES, NO LIENS AND NON-INFRINGEMENT; (B) WARRANTIES OR CONDITIONS ARISING THROUGH COURSE OF DEALING OR USAGE OF TRADE; AND (C) WARRANTIES OR CONDITIONS OF UNINTERRUPTED OR ERROR-FREE ACCESS OR USE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU THROUGH THE SERVICES OR ANY MATERIALS AVAILABLE THROUGH THE SERVICES WILL CREATE ANY WARRANTY REGARDING ANY ROOMON GROUP ENTITY OR THE SERVICES THAT IS NOT EXPRESSIVELY STATED IN THESE TERMS OF USE. YOU ASSUME ALL RISK FOR ANY DAMAGE THAT MAY RESULT FROM YOUR USE OF OR ACCESS TO THE SERVICES, YOUR DEALING WITH ANY OTHER USER, AND ANY MATERIALS, INCLUDING ALL USER AND ROOMON GROUP MATERIALS, AVAILABLE THROUGH THE SERVICES. YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES, AND USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAINMENT OF MATERIALS THROUGH THE SERVICES AND ANY ASSOCIATED SITES OR SERVICES, ARE AT YOUR OWN DISCRETION AND RISK, AND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE SERVICES), OR THE LOSS OF DATA THAT RESULTS FROM THE USE OF THE SERVICES OR THE DOWNLOAD OR USE OF THOSE MATERIALS. SOME JURISDICTIONS MAY PROHIBIT A DISCLAIMER OR WARRANTIES AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM JURSIDICTION TO JURISDICTION.

IN NO EVENT WILL ROOMON GROUP OR ANY OF ITS AFFILIATES BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, OR ANY OTHER INTANGIBLE LOSS) ARISING OUT OF, BASED ON, OR RESULTING FROM THESE TERMS OF USE OR YOUR USE OR ACCESS, OR INABILITY TO USE OR ACCESS, THE SERVICES OR ANY MATERIALS ON THE SERVICES, WHETHER BASED ON (A) BREACH OF CONTRACT, (B) BREACH OF WARRANTY, (C) NEGLIGENCE, OR (D) ANY OTHER CAUSE OF ACTION, EVEN IF ROOMON GROUP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ROOMON GROUP ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (IE) ERRORS, MISTAKES, OR INACCURACIES OF MATERIALS; (F) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE SERVICES; (G) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (H) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES; (I) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY; (J) ANY ERRORS OR OMISSIONS IN ANY MATERIALS OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY MATERIALS POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICES; AND/OR (K) USER MATERIALS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY. THE AGGREGATE LIABILITY OF ROOMON GROUP AND ANY OF ITS AFFILIATES TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE ANY PORTION OF THE SERVICES OR OTHERWISE UNDER THESE TERMS OF USE, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO THE GREATER OF: (L) THE AMOUNT YOU HAVE PAID TO ROOMON GROUP FOR THE SERVICES IN THE 12 MONTHS PRIOR TO THE EVENTS OR CIRCUMSTANCES GIVING RISE TO THE CLAIMS; ANDI (B) $100. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL DAMAGES. ACCORDINGLY, THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. EACH PROVISION OF THESE TERMS OF USE THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER THESE TERMS. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE AGREEMENT OF THE PARTIES. THE LIMITATIONS IN THIS SECTION WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS ITS ESSENTIAL PURPOSE.

14. Consent to Communications.
By using the Services, you consent to receiving certain electronic communications from Roomon Group as further described in the Privacy Policy. Please read the Privacy Policy to learn more. You agree that any notices, agreements, disclosures, or other communications that Roomon Group sends to you electronically will satisfy any legal communication requirements, including that those communications be in writing.The Services may provide web forms, links, or contact information, including phone numbers, that can connect you with Roomon Group or third parties, such as real estate agents and Lenders. Communications through these methods may be routed through a third-party service (“Communications Service”). Calls may be recorded or monitored for quality assurance and customer service purposes. You will be notified at the beginning of a call if it may be recorded or monitored. You consent to such recording and monitoring by Roomon Group or the Communications Service. Roomon Group also uses the Communications Service to track phone calls and text messages between you and real estate professionals so that Roomon Group and the real estate professional can access certain details about the contact.  As part of this process, Roomon Group and the Communications Service will receive in real time, and store, data about your call or text message, including the date and time of the call or text message, your phone number, and the content of the text message. You consent to these practices by Roomon Group and the Communications Service. The information is subject to the Privacy Policy.

15. Notice to Apple Users
If you are using our mobile applications on an iOS device, the terms of this Section 4.2 apply. You acknowledge that these Terms of Use are between you and Roomon Group only, not with Apple, and Apple is not responsible for the Services or related Materials. Apple has no obligation to furnish any maintenance or support services with respect to the Services. If the Services fail to conform to any applicable warranty, you may notify Apple and Apple will refund any applicable purchase price for the mobile application to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation with respect to the Services. Apple is not responsible for addressing any claim by you or any third party relating to the Services or your possession or use of the Services, including: (a) product liability claims; (b) any claim that the Services fail to conform to any applicable legal or regulatory requirement; and (c) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement or discharge of any third-party claim that the Services or your possession and use of the mobile application infringe that third party’s intellectual property rights. You agree to comply with any applicable third-party terms when using the Services. Apple and Apple’s subsidiaries are third party beneficiaries of Section 4.2 of these Terms of Use, and upon your acceptance of these Terms or Use, Apple will have the right (and will be deemed to have accepted the right) to enforce this Section 4.2 of these Terms of Use against you. 

16. Contact Information
The Services are offered by Roomon, Inc. and its affiliates, located at 36 Fernway Dr, Port Moody, B.C, Canada, V3H5H9. You may contact Roomon Group by sending correspondence to that address or emailing business.roomxapp@gmail.com. 

</Text>
            </ScrollView>
            <View >
              <TouchableOpacity disabled={ !isAccepted } onPress={ onPressAgreeBtn }>
                <Image source={ isAccepted ? require(assestsPath + 'agreeButtonColor.png') : require(assestsPath + 'agreeButtonGrey.png')}/>
              </TouchableOpacity>
            </View>
      </View>
      );
    }

    return agreementView();
  
}



const { width , height } = Dimensions.get('window');

const styles = StyleSheet.create({

  container:{
    marginTop: 20,
    marginLeft: 10,
    marginRight: 10,
    alignItems: 'center',
  },
  title: {
      fontSize: 22,
      alignSelf: 'center'
  },
  // tcP: {
  //     marginTop: 10,
  //     marginBottom: 10,
  //     fontSize: 12
  // },
  // tcP:{
  //     marginTop: 10,
  //     fontSize: 12
  // },
  // tcL:{
  //     marginLeft: 10,
  //     marginTop: 10,
  //     marginBottom: 10,
  //     fontSize: 12
  // },
  tcContainer: {
      // marginTop: 15,
      marginBottom: 15,
      height: height * .75
  },

  button:{
      backgroundColor: '#136AC7',
      borderRadius: 5,
      padding: 10
  },

  buttonDisabled:{
    backgroundColor: '#999',
    borderRadius: 5,
    padding: 10
 },

  buttonLabel:{
      fontSize: 14,
      color: '#FFF',
      alignSelf: 'center'
  }

})


export default Agreement;